import { Level, Badge } from './types';

export const LEVELS: Level[] = [
  {
    id: 1,
    name: 'First Spark',
    subtitle: 'Connect Your World',
    badge: '\u{1F50C}',
    badgeName: 'Connected',
    tasks: [
      {
        id: '1-1',
        title: 'Connect Gmail',
        desc: 'Connect your email to Claude. See your inbox summarized.',
        xp: 15,
        time: '2 min',
        why: 'Your inbox is where customer complaints, supplier updates, and revenue notifications live. Connecting it means Claude can summarize your morning in 10 seconds instead of 30 minutes.',
        steps: [
          { text: 'Open Claude Code and type the prompt below to connect your Gmail account.' },
          { text: 'Claude will open a Google auth window. Sign in with your business Gmail.' },
          { text: 'Once connected, ask Claude to summarize your inbox. Watch the magic.' },
        ],
        code: '/connect gmail\n\n# Then try:\n"Summarize my inbox from the last 24 hours.\nHighlight anything about orders, refunds, or supplier emails."',
      },
      {
        id: '1-2',
        title: 'Connect Google Sheets',
        desc: 'Link a spreadsheet. Pull in your order data.',
        xp: 15,
        time: '2 min',
        why: 'Google Sheets is where most D2C founders track orders, inventory, and ad spend. Once connected, Claude can read, write, and analyze your data on command.',
        steps: [
          { text: 'Run the connect command below in Claude Code.' },
          { text: 'Select the spreadsheet with your order data (or any sheet to start).' },
          { text: 'Ask Claude to read the first 10 rows to verify.' },
        ],
        code: '/connect google-sheets\n\n# Then try:\n"Read my Orders spreadsheet and tell me:\n- Total revenue this month\n- Top 3 products by units sold\n- Any orders still unfulfilled"',
      },
      {
        id: '1-3',
        title: 'Connect Shopify',
        desc: 'Link your store. See products & orders instantly.',
        xp: 20,
        time: '2 min',
        why: 'This is the big one. Connecting Shopify means Claude can see your products, orders, customers, and inventory in real time. It is like giving your AI a login to your store.',
        steps: [
          { text: 'Run the Shopify connect command. You will need your store URL.' },
          { text: 'Authorize the app in your Shopify admin.' },
          { text: 'Test it by asking Claude about your recent orders.' },
        ],
        code: '/connect shopify --store yourstore.myshopify.com\n\n# Then try:\n"Show me my last 5 orders with customer name,\nproduct, and total. Flag any that are unfulfilled."',
      },
      {
        id: '1-4',
        title: 'Connect Slack',
        desc: 'Get AI summaries of your team chat.',
        xp: 15,
        time: '2 min',
        why: "If your team uses Slack, important decisions get buried in chat. Claude can summarize channels, flag action items, and keep you in the loop without reading 200 messages.",
        steps: [
          { text: 'Run the Slack connect command.' },
          { text: 'Choose which workspace and channels to connect.' },
          { text: "Ask Claude for a summary of today's messages." },
        ],
        code: '/connect slack\n\n# Then try:\n"Summarize the #general and #orders channels from today.\nList any action items or decisions made."',
      },
      {
        id: '1-5',
        title: 'Your First Automation',
        desc: 'Auto-log new orders to a spreadsheet.',
        xp: 25,
        time: '2 min',
        why: 'This is where it clicks. Instead of manually checking Shopify, Claude will automatically log every new order to your Google Sheet. Set it and forget it.',
        steps: [
          { text: 'Make sure Shopify and Google Sheets are both connected (Tasks 1-3).' },
          { text: 'Use the prompt below to create your first automation.' },
          { text: 'Place a test order to verify it works.' },
        ],
        code: '"Create an automation that:\n1. Watches for new Shopify orders\n2. Logs each order to my \'Orders\' Google Sheet\n3. Includes: date, customer name, products, total, status\n4. Runs every 15 minutes"',
      },
    ],
  },
  {
    id: 2,
    name: 'Know Your Enemy',
    subtitle: 'Competitor Research',
    badge: '\u{1F575}\uFE0F',
    badgeName: 'Intelligence Agent',
    tasks: [
      {
        id: '2-1',
        title: "Scrape a competitor's website",
        desc: 'See their pricing, products, copy.',
        xp: 25,
        time: '5 min',
        why: "Knowing your competitor's pricing and positioning is worth thousands in saved ad spend. Claude can pull their entire product catalog in minutes.",
        steps: [
          { text: 'Pick a competitor URL — ideally a direct rival selling similar products.' },
          { text: 'Use the prompt below. Claude will crawl their site and extract key data.' },
          { text: 'Review the output. Look for pricing gaps or positioning opportunities.' },
        ],
        code: '"Go to [competitor-url.com] and extract:\n- All product names and prices\n- Their value propositions / taglines\n- Shipping policy and return policy\n- Any current sales or promotions\n\nFormat as a comparison table against my store."',
      },
      {
        id: '2-2',
        title: 'Amazon review mining',
        desc: 'Find what customers love/hate about rival products.',
        xp: 30,
        time: '5 min',
        why: "Amazon reviews are the world's biggest focus group. Mining them reveals exactly what customers want — and what your competitors are getting wrong.",
        steps: [
          { text: "Find your competitor's product (or a similar product) on Amazon." },
          { text: 'Copy the product URL and use the prompt below.' },
          { text: 'Use the insights for your own product development and copy.' },
        ],
        code: '"Analyze the reviews for this Amazon product: [URL]\n\nGive me:\n- Top 5 things customers LOVE\n- Top 5 complaints or wishes\n- Common phrases customers use (for ad copy)\n- Product improvement opportunities for my brand"',
      },
      {
        id: '2-3',
        title: 'Ad library spy',
        desc: 'See what ads your competitors are running.',
        xp: 30,
        time: '5 min',
        why: 'Your competitors are spending thousands testing ads. Why not learn from their experiments for free? The Meta Ad Library shows every active ad.',
        steps: [
          { text: 'Go to the Meta Ad Library (facebook.com/ads/library) and search your competitor.' },
          { text: 'Take note of their page name, then use Claude to analyze.' },
          { text: 'Use the insights to inform your own ad creative.' },
        ],
        code: '"Research the Facebook/Instagram ads for [competitor brand].\n\nAnalyze:\n- What hooks they use in the first 3 seconds\n- Their offer structure (discounts, bundles, etc)\n- Ad formats (video vs image vs carousel)\n- Landing page strategy\n\nSuggest 5 ad concepts I could test based on gaps."',
      },
      {
        id: '2-4',
        title: 'Build a competitor dashboard',
        desc: 'Auto-updating comparison page.',
        xp: 40,
        time: '5 min',
        why: 'Instead of manually checking competitors every week, build a dashboard that updates itself. Know the moment they change prices or launch new products.',
        steps: [
          { text: 'Choose 3-5 competitors you want to track.' },
          { text: 'Use the prompt below to create a monitoring system.' },
          { text: 'Set it to run weekly and send you a summary.' },
        ],
        code: '"Build me a competitor tracking dashboard that:\n1. Monitors these competitors: [url1], [url2], [url3]\n2. Tracks: prices, new products, site changes\n3. Updates weekly every Monday at 9am\n4. Logs changes to a Google Sheet\n5. Sends me a Slack summary of anything new"',
      },
    ],
  },
  {
    id: 3,
    name: 'Words That Sell',
    subtitle: 'Content & Copy',
    badge: '\u270D\uFE0F',
    badgeName: 'Copywriter',
    tasks: [
      {
        id: '3-1',
        title: 'Rewrite one product description',
        desc: 'AI-powered copy in your brand voice.',
        xp: 25,
        time: '5 min',
        why: 'Most product descriptions are boring feature lists. Great copy sells the feeling, not the product. Claude can rewrite yours to convert browsers into buyers.',
        steps: [
          { text: 'Pick your best-selling product (or one that is underperforming).' },
          { text: 'Feed Claude the current description plus some context about your brand.' },
          { text: 'Compare the before/after. Test the new copy on your store.' },
        ],
        code: '"Here is my current product description for [product name]:\n[paste current description]\n\nMy brand voice is [casual/premium/playful/etc].\nMy target customer is [describe them].\n\nRewrite this to:\n- Lead with the benefit, not the feature\n- Include sensory language\n- Add social proof hooks\n- End with urgency\n\nGive me 3 versions to A/B test."',
      },
      {
        id: '3-2',
        title: 'Generate 10 email subject lines',
        desc: 'A/B test ready headlines.',
        xp: 25,
        time: '5 min',
        why: 'Your subject line determines if your email gets opened. A 5% open rate difference on a 10k list means 500 more people seeing your offer.',
        steps: [
          { text: 'Decide on the email campaign (sale, new product, abandoned cart, etc).' },
          { text: 'Give Claude the context and let it generate options.' },
          { text: 'Pick your top 2-3 for A/B testing in your email platform.' },
        ],
        code: '"Generate 10 email subject lines for my [campaign type].\n\nContext:\n- Brand: [your brand]\n- Product: [what you are promoting]\n- Audience: [who they are]\n- Offer: [discount/freebie/new launch]\n\nMix these styles:\n- Curiosity gap\n- Urgency\n- Personal/conversational\n- Number-based\n- Emoji vs no emoji\n\nRate each on a predicted open rate scale."',
      },
      {
        id: '3-3',
        title: 'Build a landing page',
        desc: 'Full page from a single prompt.',
        xp: 35,
        time: '5 min',
        why: 'Landing pages convert 2-5x better than sending traffic to your homepage. Claude can build a complete, high-converting page from a single prompt.',
        steps: [
          { text: 'Define what you want the landing page for (product launch, lead magnet, sale).' },
          { text: 'Use the comprehensive prompt below.' },
          { text: 'Claude will generate full HTML/CSS. Deploy it or paste into your page builder.' },
        ],
        code: '"Build a high-converting landing page for [product/offer].\n\nInclude these sections:\n1. Hero with headline, subhead, and CTA button\n2. Problem/agitation section\n3. Product showcase with benefits\n4. Social proof (review placeholders)\n5. FAQ section\n6. Final CTA with urgency\n\nStyle: modern, clean, mobile-first.\nBrand colors: [your colors]\nOutput as a single HTML file with inline CSS."',
      },
      {
        id: '3-4',
        title: 'Instagram content calendar',
        desc: '30 days of posts planned.',
        xp: 35,
        time: '5 min',
        why: 'Consistency on Instagram is everything, but planning content is a time sink. Claude can generate a full month of strategic posts in minutes.',
        steps: [
          { text: 'Share your brand context and content pillars with Claude.' },
          { text: 'Use the prompt to generate a full 30-day calendar.' },
          { text: 'Review, tweak, and schedule using your favorite tool.' },
        ],
        code: '"Create a 30-day Instagram content calendar for [brand].\n\nContent pillars:\n1. Product showcases\n2. Behind-the-scenes\n3. Customer stories/UGC\n4. Educational/tips\n5. Promotional\n\nFor each day include:\n- Post type (reel/carousel/story/static)\n- Caption with hashtags\n- Visual direction\n- Best posting time\n\nFormat as a table: Day | Type | Caption | Visual | Time"',
      },
    ],
  },
  {
    id: 4,
    name: 'Autopilot',
    subtitle: 'Your First Agent',
    badge: '\u{1F916}',
    badgeName: 'Agent Builder',
    tasks: [
      {
        id: '4-1',
        title: 'Morning briefing agent',
        desc: 'Daily summary of orders, revenue, issues.',
        xp: 40,
        time: '10 min',
        why: 'Imagine waking up to a complete business briefing — orders, revenue, issues, opportunities — without opening a single app. That is what this agent does.',
        steps: [
          { text: 'Make sure your key integrations (Shopify, Gmail, Sheets) are connected.' },
          { text: 'Use the prompt below to create your morning briefing agent.' },
          { text: 'Set it to run at your preferred wake-up time.' },
        ],
        code: '"Create a morning briefing agent that runs daily at 7am and sends me a summary:\n\nRevenue: yesterday\'s sales, vs. 7-day avg\nOrders: new orders, fulfillment status\nAlerts: low inventory, refund requests, bad reviews\nEmail: important messages needing response\nTrends: anything unusual in traffic or conversion\n\nSend the briefing to my Slack #ceo-briefing channel."',
      },
      {
        id: '4-2',
        title: 'Customer complaint handler',
        desc: 'Auto-draft responses to angry emails.',
        xp: 40,
        time: '10 min',
        why: 'Responding to complaints fast keeps customers. This agent detects angry emails and drafts empathetic, on-brand responses for your approval.',
        steps: [
          { text: 'Connect your customer support email (Gmail or helpdesk).' },
          { text: 'Set up the complaint detection agent.' },
          { text: 'Review drafts before they send — you stay in control.' },
        ],
        code: '"Create an agent that monitors my inbox for customer complaints.\n\nWhen a negative/complaint email is detected:\n1. Classify severity (minor/major/critical)\n2. Draft a response that is empathetic, solution-oriented\n3. Include a resolution offer based on our policy:\n   - Minor: apology + 10% discount code\n   - Major: replacement or full refund\n   - Critical: escalate to me immediately\n4. Save draft for my review (don\'t auto-send)\n5. Log to \'Complaints\' Google Sheet"',
      },
      {
        id: '4-3',
        title: 'Price monitoring agent',
        desc: 'Track competitor prices daily.',
        xp: 45,
        time: '10 min',
        why: 'Competitor price changes are signals — new inventory, desperation, or strategy shifts. Know about changes the same day, not weeks later.',
        steps: [
          { text: 'List the competitor products you want to monitor (URLs).' },
          { text: 'Create the price monitoring agent.' },
          { text: 'You will get alerts only when prices change — no noise.' },
        ],
        code: '"Build a price monitoring agent that:\n1. Checks these competitor products daily:\n   - [product URL 1]\n   - [product URL 2]\n   - [product URL 3]\n2. Logs current price to \'Price Tracking\' Google Sheet\n3. Alerts me via Slack ONLY when a price changes\n4. Includes: product name, old price, new price, % change\n5. Weekly summary every Friday of all tracked prices"',
      },
      {
        id: '4-4',
        title: 'Your personal Jarvis',
        desc: 'An AI that knows your business inside out.',
        xp: 50,
        time: '10 min',
        why: 'This is the culmination — a custom AI assistant that knows your products, customers, competitors, and goals. Ask it anything about your business and get instant answers.',
        steps: [
          { text: 'Gather your key business documents (brand guide, product catalog, customer data).' },
          { text: 'Create your personalized business AI using the prompt below.' },
          { text: 'Test it with real business questions. It should feel like talking to a COO.' },
        ],
        code: '"Create my personal business AI assistant with this context:\n\nBusiness: [your brand name and what you sell]\nTarget customer: [demographics, psychographics]\nRevenue: [monthly revenue range]\nProducts: [connect to Shopify for live data]\nKey metrics: [what you track]\nGoals: [90-day goals]\nCompetitors: [top 3 competitors]\n\nThis AI should:\n- Answer any question about my business using real data\n- Make recommendations backed by numbers\n- Flag opportunities and risks proactively\n- Have the context of a COO who knows everything"',
      },
    ],
  },
];

export const BADGES: Badge[] = LEVELS.map((l) => ({
  levelId: l.id,
  emoji: l.badge,
  name: l.badgeName,
}));
